"""
QC Report Generation Module

Generate HTML reports for harmonization quality assessment.
"""

from pathlib import Path
from typing import Dict, Optional, List
from datetime import datetime


HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <title>RISH Harmonization QC Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
        }
        .section {
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .section h2 {
            color: #333;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
        }
        .metric-card {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }
        .metric-value {
            font-size: 24px;
            font-weight: bold;
            color: #667eea;
        }
        .metric-label {
            color: #666;
            font-size: 14px;
        }
        .status-good { color: #28a745; }
        .status-warn { color: #ffc107; }
        .status-bad { color: #dc3545; }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #f8f9fa;
        }
        .figure {
            text-align: center;
            margin: 20px 0;
        }
        .figure img {
            max-width: 100%;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .footer {
            text-align: center;
            color: #666;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🧠 RISH Harmonization QC Report</h1>
        <p>Generated: {timestamp}</p>
    </div>
    
    <div class="section">
        <h2>📊 Summary Metrics</h2>
        <div class="metrics-grid">
            {metrics_html}
        </div>
    </div>
    
    <div class="section">
        <h2>📁 Input/Output Files</h2>
        <table>
            <tr><th>File</th><th>Path</th></tr>
            {files_html}
        </table>
    </div>
    
    <div class="section">
        <h2>⚙️ Parameters</h2>
        <table>
            <tr><th>Parameter</th><th>Value</th></tr>
            {params_html}
        </table>
    </div>
    
    {figures_html}
    
    <div class="footer">
        <p>Generated by mrtrix-rish v0.1.0</p>
    </div>
</body>
</html>
"""


def generate_html_report(
    metrics: Dict[str, float],
    files: Dict[str, str],
    params: Dict[str, any],
    output_path: str,
    figures: Optional[List[str]] = None
) -> str:
    """
    Generate HTML QC report.
    
    Parameters
    ----------
    metrics : dict
        QC metrics (name -> value)
    files : dict
        Input/output files (label -> path)
    params : dict
        Processing parameters
    output_path : str
        Output HTML file path
    figures : list of str, optional
        Paths to figure images
        
    Returns
    -------
    str
        Path to generated report
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Generate metrics HTML
    metrics_html = ""
    for name, value in metrics.items():
        if value is not None:
            if isinstance(value, float):
                value_str = f"{value:.4f}"
            else:
                value_str = str(value)
            
            metrics_html += f"""
            <div class="metric-card">
                <div class="metric-value">{value_str}</div>
                <div class="metric-label">{name.replace('_', ' ').title()}</div>
            </div>
            """
    
    # Generate files HTML
    files_html = ""
    for label, path in files.items():
        files_html += f"<tr><td>{label}</td><td><code>{path}</code></td></tr>\n"
    
    # Generate params HTML
    params_html = ""
    for name, value in params.items():
        params_html += f"<tr><td>{name}</td><td>{value}</td></tr>\n"
    
    # Generate figures HTML
    figures_html = ""
    if figures:
        figures_html = '<div class="section"><h2>📈 Figures</h2>'
        for fig in figures:
            fig_name = Path(fig).stem
            figures_html += f'''
            <div class="figure">
                <img src="{fig}" alt="{fig_name}">
                <p>{fig_name}</p>
            </div>
            '''
        figures_html += '</div>'
    
    # Fill template
    html = HTML_TEMPLATE.format(
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        metrics_html=metrics_html,
        files_html=files_html,
        params_html=params_html,
        figures_html=figures_html
    )
    
    with open(output_path, "w") as f:
        f.write(html)
    
    return str(output_path)
